run_tests_on_start: false
paths:
  layout: "./pyscript/layout.yml"
  rules: "./pyscript/rules.yml"
  devices: "./pyscript/devices.yml"
  connections: "./pyscript/connections.yml"
  sun: "./pyscript/sun_config.yml"
